USE mysql;

DROP FUNCTION IF EXISTS lib_mysqludf_crypt_info;
DROP FUNCTION IF EXISTS sha256;
DROP FUNCTION IF EXISTS sha384;
DROP FUNCTION IF EXISTS sha512;
DROP FUNCTION IF EXISTS sha3;
DROP FUNCTION IF EXISTS blake2;
DROP FUNCTION IF EXISTS argon2;
DROP FUNCTION IF EXISTS scrypt;